services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: "no"
    networks:
      - p105_queue_private
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

networks:
  p105_queue_private:
    internal: true
