"""Stable public contract manifest for the bounded OpsCat release surface."""

from __future__ import annotations

from typing import Any

from app.services.p110_evaluation import stable_hash

PUBLIC_CONTRACT_VERSION = "1.0.0"
REQUIRED_PUBLIC_CONTRACTS = {
    "cli": "command",
    "connector-sdk": "extension",
    "p115-action-pack": "schema",
    "release-evidence": "evidence",
    "configuration": "configuration",
    "policy-packs": "policy-pack",
    "incident": "incident",
    "evidence": "evidence",
    "approval": "approval",
    "validation": "validation",
    "rollback": "rollback",
    "learning": "learning",
    "replay": "replay",
    "observability": "observability",
    "frozen-eval": "frozen-eval",
}


def public_contract_manifest() -> dict[str, Any]:
    common = {
        "stability": "stable-v1",
        "backward_compatibility": "additive changes within 0.2.x; breaking changes require a major contract version",
        "deprecation": "documented for at least one minor release before removal",
        "nonlocal_authority_allowed": False,
        "release_evidence_ref": "evals/p122/release-evidence.json",
    }
    contracts = [
        {
            **common,
            "name": "cli",
            "category": "command",
            "owner_module": "app.cli",
            "owner_symbol": "main",
            "interface_ref": "opscat --help",
            "authority_level": "L0 local evidence and replay only",
            "test_ref": "tests/test_p122_public_contracts.py",
            "doc_ref": "docs/public-contracts.md",
        },
        {
            **common,
            "name": "connector-sdk",
            "category": "extension",
            "owner_module": "app.plugin_sdk",
            "owner_symbol": "ReadOnlyConnectorV1",
            "interface_ref": "ReadOnlyConnectorV1",
            "authority_level": "L0 read-only",
            "test_ref": "tests/test_p122_public_contracts.py",
            "doc_ref": "docs/public-contracts.md",
        },
        {
            **common,
            "name": "p115-action-pack",
            "category": "schema",
            "owner_module": "app.services.p115_action_contract",
            "owner_symbol": "build_p115_action_proposal",
            "interface_ref": "p115.action_proposal.v1",
            "authority_level": "declarative only",
            "test_ref": "tests/test_p115_action_contract.py",
            "doc_ref": "docs/operations/p115-outcome-grounded-remediation-roadmap.md",
        },
        {
            **common,
            "name": "release-evidence",
            "category": "evidence",
            "owner_module": "app.services.p122_release_evidence",
            "owner_symbol": "produce_p122_release_evidence",
            "interface_ref": "p122.release_evidence.v1",
            "authority_level": "L0 evidence",
            "test_ref": "tests/test_p122_release_evidence.py",
            "doc_ref": "docs/release-evidence.md",
        },
        {
            **common,
            "name": "configuration",
            "category": "configuration",
            "owner_module": "app.config",
            "owner_symbol": "Settings",
            "interface_ref": "app.config.Settings",
            "authority_level": "local configuration; fail-closed production-like demo targets",
            "test_ref": "tests/test_p122_public_contracts.py",
            "doc_ref": "docs/install.md",
        },
        {
            **common,
            "name": "policy-packs",
            "category": "policy-pack",
            "owner_module": "app.services.p115_ontology",
            "owner_symbol": "ACTION_PACK_SCHEMA_VERSION",
            "interface_ref": "p115.action_pack.v1",
            "authority_level": "signed declarative candidate only",
            "test_ref": "tests/test_p115_ontology.py",
            "doc_ref": "docs/operations/p115-outcome-grounded-remediation-roadmap.md",
        },
        {
            **common,
            "name": "incident",
            "category": "incident",
            "owner_module": "app.services.p115_ontology",
            "owner_symbol": "INCIDENT_CASE_SCHEMA_VERSION",
            "interface_ref": "p115.incident_case.v1",
            "authority_level": "fixture incident evidence only",
            "test_ref": "tests/test_p115_ontology.py",
            "doc_ref": "docs/operations/p115-outcome-grounded-remediation-roadmap.md",
        },
        {
            **common,
            "name": "evidence",
            "category": "evidence",
            "owner_module": "app.services.p121_forecasting",
            "owner_symbol": "P121_EVIDENCE_SCHEMA_VERSION",
            "interface_ref": "p121.evidence_receipt.v1",
            "authority_level": "read-only evidence receipt",
            "test_ref": "tests/test_p121_forecasting.py",
            "doc_ref": "docs/tickets/p121/P121-002-evidence-acquisition-before-intervention.md",
        },
        {
            **common,
            "name": "approval",
            "category": "approval",
            "owner_module": "app.services.p121_execution",
            "owner_symbol": "P121_APPROVAL_SCHEMA_VERSION",
            "interface_ref": "p121.approval.v1",
            "authority_level": "deterministic local fixture approval",
            "test_ref": "tests/test_p121_execution.py",
            "doc_ref": "docs/tickets/p121/P121-005-deterministic-approval-and-l0-l3-local-sandbox-intervention.md",
        },
        {
            **common,
            "name": "validation",
            "category": "validation",
            "owner_module": "app.services.p121_validation",
            "owner_symbol": "validate_prevention_outcome",
            "interface_ref": "p121.validation_outcome.v1",
            "authority_level": "measured local validation only",
            "test_ref": "tests/test_p121_validation.py",
            "doc_ref": "docs/tickets/p121/P121-006-validation-rollback-causal-attribution-and-recurrence-reduction.md",
        },
        {
            **common,
            "name": "rollback",
            "category": "rollback",
            "owner_module": "app.services.p121_validation",
            "owner_symbol": "validate_prevention_outcome",
            "interface_ref": "p121.validation_outcome.v1#/rollback",
            "authority_level": "fail-closed local rollback result",
            "test_ref": "tests/test_p121_validation.py",
            "doc_ref": "docs/tickets/p121/P121-006-validation-rollback-causal-attribution-and-recurrence-reduction.md",
        },
        {
            **common,
            "name": "learning",
            "category": "learning",
            "owner_module": "app.services.p119_attribution",
            "owner_symbol": "build_p119_learning_record",
            "interface_ref": "p119.offline_learning_record.v1",
            "authority_level": "offline record; online policy writes disabled",
            "test_ref": "tests/test_p119_attribution.py",
            "doc_ref": "docs/tickets/p119/P119-007-causal-outcome-attribution-recurrence-and-learning.md",
        },
        {
            **common,
            "name": "replay",
            "category": "replay",
            "owner_module": "app.services.p121_execution",
            "owner_symbol": "prove_p121_restart_recovery",
            "interface_ref": "p121.restart_recovery_proof.v1",
            "authority_level": "read-only deterministic fixture replay",
            "test_ref": "tests/test_p121_execution.py",
            "doc_ref": "docs/tickets/p121/P121-008-docs-test-spec-release-evidence-crash-replay-and-independent-review.md",
        },
        {
            **common,
            "name": "observability",
            "category": "observability",
            "owner_module": "scripts.run_p122_performance_soak",
            "owner_symbol": "PERFORMANCE_SOAK_SCHEMA_VERSION",
            "interface_ref": "p122.performance_soak.v2#/observability",
            "authority_level": "local health, metrics, redacted logs, and diagnostics",
            "test_ref": "tests/test_p122_performance_soak.py",
            "doc_ref": "docs/performance.md",
        },
        {
            **common,
            "name": "frozen-eval",
            "category": "frozen-eval",
            "owner_module": "app.services.p121_evaluator",
            "owner_symbol": "P121_EVALUATION_SCHEMA_VERSION",
            "interface_ref": "p121.frozen_prevention_evaluation.v1",
            "authority_level": "offline frozen evaluation only",
            "test_ref": "tests/test_p121_evaluator_release_evidence.py",
            "doc_ref": "docs/tickets/p121/P121-007-frozen-unseen-temporal-system-evaluation.md",
        },
    ]
    manifest: dict[str, Any] = {
        "schema_version": "opscat.public_contracts.v1",
        "contract_version": PUBLIC_CONTRACT_VERSION,
        "required_contracts": REQUIRED_PUBLIC_CONTRACTS,
        "contracts": contracts,
    }
    manifest["manifest_hash"] = stable_hash(manifest)
    return manifest


__all__ = ["PUBLIC_CONTRACT_VERSION", "REQUIRED_PUBLIC_CONTRACTS", "public_contract_manifest"]
